name: py39
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - altair=4.1.0=py_1
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=21.1.0=py39h3811e60_2
  - arrow-cpp=6.0.1=py39h9adb24c_2_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - aws-c-auth=0.6.7=hfef2836_0
  - aws-c-cal=0.5.12=h70efedd_7
  - aws-c-common=0.6.17=h7f98852_0
  - aws-c-compression=0.2.14=h7c7754b_7
  - aws-c-event-stream=0.2.7=hb80ed28_31
  - aws-c-http=0.6.10=h58a30cf_2
  - aws-c-io=0.10.13=he836878_5
  - aws-c-mqtt=0.7.9=h042a236_0
  - aws-c-s3=0.1.27=hae5f17b_11
  - aws-c-sdkutils=0.1.1=h7c7754b_4
  - aws-checksums=0.1.12=h7c7754b_6
  - aws-crt-cpp=0.17.8=h82bac0c_1
  - aws-sdk-cpp=1.9.148=hfe59705_0
  - backcall=0.2.0=py_0
  - base58=2.1.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - boost-cpp=1.74.0=h312852a_4
  - boto3=1.20.11=pyhd8ed1ab_0
  - botocore=1.23.12=pyhd8ed1ab_0
  - bottleneck=1.3.2=py39hdd57654_1
  - branca=0.4.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h3811e60_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.15.0=py39h4bc2ebd_0
  - cfitsio=3.470=h2e3daa1_7
  - chardet=4.0.0=py39hf3d152e_2
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cryptography=35.0.0=py39h95dcef6_2
  - curl=7.80.0=h2574ce0_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - daal4py=2021.3.0=py39hae6d005_0
  - dal=2021.3.0=h06a4308_557
  - debugpy=1.5.1=py39h295c915_0
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - fiona=1.8.20=py39h494ca2c_0
  - folium=0.12.1.post1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - gdal=3.2.2=py39h409cc32_9
  - geopandas=0.10.2=pyhd8ed1ab_0
  - geopandas-base=0.10.2=pyha770c72_0
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=h4f31c25_6
  - gettext=0.19.8.1=h73d1719_1008
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - glog=0.5.0=h48cff8f_0
  - grpc-cpp=1.42.0=h7e358d9_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - icu=68.2=h9c3ff4c_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.2=py39hf3d152e_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.4.1=py39h06a4308_1
  - ipython=7.29.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py39h06a4308_1
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - jsonschema=4.2.1=pyhd8ed1ab_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.9.1=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kealib=1.4.14=hcc255d8_2
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=hcc1bbae_3
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcurl=7.80.0=h2574ce0_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgdal=3.2.2=h358be1b_9
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libglib=2.70.1=h174f98d_0
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1014
  - libnetcdf=4.8.1=nompi_hcd642e3_100
  - libnghttp2=1.43.0=h812cca2_1
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_3
  - libprotobuf=3.18.1=h780b84a_0
  - librttopo=1.1.0=h1185371_6
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=h8694cbe_6
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libthrift=0.15.0=he6d91bd_1
  - libtiff=4.3.0=h6f004c6_2
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_1
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h3811e60_1
  - matplotlib-base=3.4.3=py39h2fa2bec_2
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h3811e60_1005
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mpi=1.0=mpich
  - mpich=3.3.2=hc856adb_0
  - munch=2.5.0=py_0
  - nbclient=0.5.9=pyhd8ed1ab_0
  - nbconvert=6.3.0=py39hf3d152e_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.4.6=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.72=hb5efdd6_0
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - orc=1.7.1=h68e2c4e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.4=py39h8c16a72_0
  - pandoc=2.16.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.0=py_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py39ha612740_0
  - pip=21.2.4=py37h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=21.09.0=ha39eefc_3
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=13.3=h2510834_3
  - proj=8.0.1=h277dcde_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.8=py_0
  - protobuf=3.18.1=py39he80948d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyarrow=6.0.1=py39hff6fa39_2_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeck=0.7.0=pyh6c4a22f_0
  - pygments=2.7.1=py_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyproj=3.2.1=py39ha9a7ae0_5
  - pyrsistent=0.18.0=py39h3811e60_0
  - pysocks=1.7.1=py39hf3d152e_4
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2021.5=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd3eb1b0_0
  - pytz-deprecation-shim=0.1.0.post0=py39hf3d152e_1
  - pyyaml=6.0=py39h3811e60_3
  - pyzmq=20.0.0=py39h2531618_1
  - re2=2021.11.01=h9c3ff4c_0
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd8ed1ab_0
  - rtree=0.9.7=py39hb102c33_2
  - s2n=1.3.0=h9b69904_0
  - s3transfer=0.5.0=pyhd8ed1ab_0
  - scikit-learn=1.0.1=py39h51133e4_0
  - scikit-learn-intelex=2021.3.0=py39h06a4308_0
  - scipy=1.7.1=py39h292c36d_2
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=52.0.0=py39h06a4308_0
  - shapely=1.8.0=py39ha61afbd_0
  - six=1.16.0=pyhd3eb1b0_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.36.0=hc218d9a_0
  - statsmodels=0.13.1=py39hce5d2b2_0
  - streamlit=0.84.1=pyhd8ed1ab_0
  - streamlit-folium=0.4.0=pyhd8ed1ab_0
  - tbb=2021.4.0=hd09550d_0
  - terminado=0.12.1=py39hf3d152e_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tiledb=2.3.4=he87e0bf_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py39h3811e60_2
  - traitlets=5.0.5=py_0
  - typing_extensions=4.0.0=pyha770c72_0
  - tzcode=2021e=h7f98852_0
  - tzdata=2021a=h5d7bf9c_0
  - tzlocal=4.1=py39hf3d152e_1
  - urllib3=1.26.7=pyhd8ed1ab_0
  - validators=0.18.2=pyhd3deb0d_0
  - watchdog=2.1.6=py39hf3d152e_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.2=py39hf3d152e_1
  - xerces-c=3.2.3=h9d8b166_3
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2021.11.0=pyhd8ed1ab_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - backports-entry-points-selectable==1.1.0
    - distlib==0.3.2
    - docopt==0.6.2
    - filelock==3.0.12
    - pipenv==2021.5.29
    - pipreqs==0.4.11
    - platformdirs==2.3.0
    - virtualenv==20.7.2
    - virtualenv-clone==0.5.7
    - yarg==0.1.9
prefix: /home/research-lab/anaconda2/envs/py39

